export default ({ store }) => {
  store.commit('steemqa/serverURL', 'http://localhost:8000')
  store.commit('steemqa/appName', 'StemQA')
  store.commit('steemqa/topics', {
    'Science': {
      'Astronomy': [
        'Astrobiology',
        'Astrometry',
        'Astrophysics',
        'Observational astronomy',
        'Photometry',
        'Planetary Science',
        'Spectroscopy'
      ],
      'Biology': [
        'Biochemistry',
        'Biophysics',
        'Botany',
        'Genetics',
        'Microbiology',
        'Molecular biology'
      ],
      'Chemistry': [
        'Analytical chemistry',
        'Inorganic chemistry',
        'Nuclear chemistry',
        'Organic chemistry',
        'Physical chemistry'
      ],
      'Computer science': [
      ],
      'Ecology': [
      ],
      'Geography': [
      ],
      'Geology': [
        'Geologic provinces',
        'Geology of Earth',
        'History of geology',
        'Planetary geology',
        'Plate tectonics',
        'Principles of geology'
      ],
      'Physics': [
        'Accelerator physics',
        'Acoustics',
        'Aerodynamics',
        'Agrophysics',
        'Astrodynamics',
        'Astrometry',
        'Astronomy',
        'Astrophysics',
        'Atmospheric physics',
        'Atomic, molecular, and optical physics',
        'Biomechanics',
        'Biophysics',
        'Chemical physics',
        'Classical mechanics',
        'Classical physics',
        'Computational physics',
        'Condensed matter physics',
        'Continuum mechanics',
        'Cryogenics',
        'Dynamics',
        'Econophysics',
        'Electromagnetism',
        'Extragalactic astronomy',
        'Fluid dynamics',
        'Fluid kinematics',
        'Fluid mechanics',
        'Fluid statics',
        'Galactic astronomy',
        'Geophysics',
        'Homeokinetics',
        'Kinematics',
        'Materials physics',
        'Mathematical physics',
        'Mechanics',
        'Medical physics',
        'Neurophysics',
        'Nuclear physics',
        'Optics',
        'Particle physics',
        'Physical cosmology',
        'Planetary science',
        'Plasma physics',
        'Polymer physics',
        'Psychophysics',
        'Quantum mechanics',
        'Quantum physics',
        'Relativity',
        'Soil physics',
        'Solid state physics',
        'Statics',
        'Stellar astronomy',
        'Theoretical physics',
        'Thermodynamics',
        'Thermodynamics',
        'Vehicle dynamics'
      ],
      'Psychology': [
      ],
      'Sociology': [
      ],
      'Zoology': [
      ]
    },
    'Technology': {
      'Agricultural technology': [],
      'Assistive technology': [],
      'Balancing technology': [],
      'Banking technology': [],
      'Biotechnology': [],
      'Building technology': [],
      'Cleaning methods': [],
      'Cleanroom technology': [],
      'Consumer electronics': [],
      'Cybernetics': [],
      'Domestic implements': [],
      'Drilling technology': [],
      'Educational technology': [],
      'Electronics': [],
      'Emerging technologies': [],
      'Energy technology': [],
      'Environmental technology': [],
      'Equipment': [],
      'Explosives': [],
      'Film and video technology': [],
      'Financial technology': [],
      'Fluid technology': [],
      'Food technology': [],
      'Gas turbine technology': [],
      'Geographical technology': [],
      'Home automation': [],
      'Industry': [],
      'Information and communications technology': [],
      'Inventions': [],
      'Machinery': [],
      'Medical technology': [],
      'Microtechnology': [],
      'Military technology': [],
      'Mining techniques': [],
      'Missile technology': [],
      'Music technology': [],
      'Nanotechnology': [],
      'Political campaign technology': [],
      'Primitive technology': [],
      'Rail technologies': [],
      'Scientific equipment': [],
      'Sound technology': [],
      'Space technology': [],
      'Sports technology': [],
      'Tools': [],
      'Transport': [],
      'Travel technology': [],
      'Vehicle technology': [],
      'Waste treatment technology': []
    },
    'Engineering': {
      'Acoustical engineering': [],
      'Aerospace engineering': [],
      'Agricultural engineering': [],
      'Air conditioning': [],
      'Applied engineering': [],
      'Automotive engineering': [],
      'Avionics': [],
      'Biological engineering': [],
      'Biomechatronics engineering': [],
      'Biomedical engineering': [],
      'Biomolecular engineering': [],
      'Building services engineering': [],
      'Cameras': [],
      'Computer engineering': [],
      'Control engineering': [],
      'Corrosion engineering': [],
      'Cryptographic engineering': [],
      'Digital electronics systems engineering': [],
      'Ecological engineering': [],
      'Electronic engineering': [],
      'Energy engineering': [],
      'Environmental engineering': [],
      'Fiber optics': [],
      'Geotechnical engineering': [],
      'Hardware engineering': [],
      'Heating, ventilating': [],
      'Industrial engineering': [],
      'Instrumentation engineering': [],
      'Laser systems': [],
      'Manufacturing engineering': [],
      'Marine engineering': [],
      'Materials engineering': [],
      'Military engineering': [],
      'Mining engineering': [],
      'Molecular engineering': [],
      'Municipal or urban engineering': [],
      'Nanoengineering': [],
      'Naval architecture': [],
      'Network engineering': [],
      'Nuclear engineering': [],
      'Optical engineering': [],
      'Optical instrumentation': [],
      'Optomechanical engineering': [],
      'Optomechatronics engineering': [],
      'Petroleum engineering': [],
      'Power engineering': [],
      'Power plant engineering': [],
      'Programming': [
        'C',
        'C#',
        'C++',
        'Delphi',
        'Fortran',
        'Go',
        'Groovy',
        'Java',
        'JavaScript',
        'Lisp',
        'Matlab',
        'Objective-C',
        'Perl',
        'PHP',
        'Python',
        'R',
        'Ruby',
        'Swift',
        'Visual Basic',
        'Visual Basic .NET'
      ],
      'Railway engineering': [],
      'Refrigeration': [],
      'Robotics': [],
      'Software engineering': [],
      'Solar engineering': [],
      'Sports engineering': [],
      'Telecommunications engineering': [],
      'Telescopes': [],
      'Thermal engineering': [],
      'Transport engineering': [],
      'Vehicle engineering': [],
      'Water resources engineering': [],
      'Wind engineering': []
    },
    'Mathematics': {
      'Algebra': [],
      'Algebraic geometry': [],
      'Analysis': [],
      'Applied mathematics': [],
      'Arithmetic': [],
      'Calculus': [],
      'Combinatorics': [],
      'Commutative rings and algebras': [],
      'Convex geometry and discrete geometry': [],
      'Differential geometry': [],
      'Discrete or combinatorial geometry': [],
      'Field theory and polynomials': [],
      'Fluid mechanics': [],
      'General algebraic systems': [],
      'Mechanics': [],
      'Mechanics of deformable solids': [],
      'Mechanics of structures': [],
      'Model theory': [],
      'Number theory': [],
      'Numerical analysis': [],
      'Order theory': [],
      'Particle mechanics': [],
      'Physical sciences': [],
      'Probability and statistics': [],
      'Proof theory and constructive mathematics': [],
      'Recreational mathematics': [],
      'Set theory': [],
      'Topology': []
    }
  })
}
